name: PixEz Windows自动打包
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: 拉取仓库源码
        uses: actions/checkout@v4

      - name: 配置Flutter稳定版本
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: 云端自动安装C++编译工具
        run: choco install visualstudio2022-buildtools visualstudio2022-workload-vctools -y

      - name: 安装项目依赖包
        run: flutter pub get

      - name: 编译Windows正式版程序
        run: flutter build windows --release

      - name: 打包成品为压缩包
        run: Compress-Archive build/windows/x64/release PixEz_Windows.zip

      - name: 上传打包文件（可下载）
        uses: actions/upload-artifact@v4
        with:
          name: PixEz-Windows客户端
          path: PixEz_Windows.zip
