name: PixEz Windows打包
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4

      - name: 配置Flutter稳定版
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # 关键：强制指定VS路径，解决检测不到VS的报错
      - name: 配置Visual Studio路径
        run: flutter config --windows-vs-path "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"

      - name: 验证环境
        run: flutter doctor

      - name: 安装项目依赖
        run: flutter pub get

      - name: 编译Windows正式版
        run: flutter build windows --release

      - name: 压缩成品
        run: Compress-Archive build/windows/x64/release PixEz_Windows成品.zip

      - name: 上传下载包
        uses: actions/upload-artifact@v4
        with:
          name: PixEz-Windows客户端
          path: PixEz_Windows成品.zip
