name: Flutter Windows打包

on:
  push:
    branches: [ master ]
  workflow_dispatch: # 支持手动点运行

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./ # 指定项目根目录，解决报错
    steps:
      # 1.拉取代码
      - name: 拉取源码
        uses: actions/checkout@v4

      # 2.配置Flutter环境
      - name: 安装Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # 改成你自己的flutter版本

      # 3.关闭分析统计（避免多余弹窗输出）
      - name: 关闭Flutter Analytics
        run: flutter config --no-analytics

      # 4.安装依赖（你报错的这一步）
      - name: 安装项目依赖
        run: flutter pub get

      # 5.编译Windows Release安装包
      - name: 编译Windows Release
        run: flutter build windows --release

      # 6.压缩打包产物
      - name: 压缩安装包
        run: |
          choco install 7zip -y --no-progress
          7z a Flutter-Windows-release.zip ./build/windows/x64/runner/Release/*

      # 7.上传成品文件
      - name: 上传打包文件
        uses: actions/upload-artifact@v4
        with:
          name: Windows安装包
          path: Flutter-Windows-release.zip
