name: PixEz Windows打包
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4

      - name: 配置Flutter稳定版
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: 验证环境
        run: flutter doctor -v

      - name: 安装项目依赖
        run: flutter pub get

      - name: 编译Windows正式版
        run: flutter build windows --release

      # 修正路径，加上 runtime
      - name: 压缩成品
        run: Compress-Archive build/windows/x64/runtime/release PixEz_Windows成品.zip

      - name: 上传下载包
        uses: actions/upload-artifact@v4
        with:
          name: PixEz-Windows客户端
          path: PixEz_Windows成品.zip
